---
kind: pipeline
name: Merged

steps:
  - name: build
    image: node:14.5.0-alpine3.10
    commands:
      - yarn
      - yarn build
      - yarn test

---
kind: pipeline
name: Tag and Deploy to NPM

steps:
  - name: Do Deploy
    image: node:14.5.0-alpine3.10
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - yarn config set registry https://registry.npmjs.com/:_authToken=$NPM_TOKEN
      - yarn
      - yarn build
      - yarn test
      - rm yarn.lock
      - npm version $DRONE_TAG
      - npm publish
    secrets:
      - npm_token

trigger:
  event:
    - tag
