---
kind: pipeline
name: Merged

steps:
  - name: build
    image: node:14.5.0-alpine3.10
    commands:
      - yarn
      - yarn build
      - yarn test
trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
name: Tag and Deploy to NPM

steps:
  - name: Do Deploy
    image: node:14.5.0-alpine3.10
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" > .npmrc
      - yarn
      - yarn build
      - yarn test
      - npm version $DRONE_TAG
      - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm publish --access public --verbose
    secrets:
      - npm_token
trigger:
  event:
    - tag
