---
kind: pipeline
name: Merged

steps:
  - name: build
    image: node:14.5.0-alpine3.10
    commands:
      - yarn
      - yarn build
      - yarn test

  - name: Do Deploy
    image: node:14.5.0-alpine3.10
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
      - yarn
      - yarn build
      - yarn test
      - rm yarn.lock
      - npm version $DRONE_TAG
      - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      - npm publish --access public --verbose
    secrets:
      - npm_token

---
kind: pipeline
name: Tag and Deploy to NPM

steps:
  - name: Do Deploy
    image: node:14.5.0-alpine3.10
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
      - yarn
      - yarn build
      - yarn test
      - rm yarn.lock
      - npm version $DRONE_TAG
      - npm whoami
      - npm publish --access public
    secrets:
      - npm_token

trigger:
  event:
    - tag
